User Registration Page Fixes
mitre-cyber-academy/ctf-scoreboard pull request #787
Opened 2021-12-03 00:11 UTC by Domur

Fixed the user registration page not enforcing any password requirements and not hiding the states dropdown if US wasn't selected as country

2021-12-04 00:40 UTC, Domur commented
Filterrific was throwing off the state dropdown functionality because it throws an exception trying to dispatch an event on an element "filterrific_state" that doesn't exist. For the time being I just commented out the filterrific part, which seems to not have affected anything, but there might be some some unintended effects I just haven't seen yet.

2021-12-06 16:46 UTC, rbclark requested changes
Could you fix the tests on this?

The `filterifficShowHideState` function is there in order to show or hide the state on the team finder page, removing it will likely cause that page to break. It would be better to fix that function to not cause an error.

2021-12-06 20:57 UTC, Domur commented
> Could you fix the tests on this?
> 
> The `filterifficShowHideState` function is there in order to show or hide the state on the team finder page, removing it will likely cause that page to break. It would be better to fix that function to not cause an error.

Yeah I've trying to figure out what's going on with the tests before finalizing this, not sure what it doesn't like. And I see what you mean about where filterrific is used, will adjust the code so it works in both cases.

2021-12-07 22:25 UTC, rbclark approved these changes

2021-12-07 22:28 UTC, merged